### PR TITLE
Adding test script #65

### PR DESCRIPTION
**Pull request by stork119**
Test script performs analysis on standard input configuration_settings
located in IPIQA/tests/ directory.

### CODE REVIEW

**Comment by stork119** [comment]
@Setnea what is a size of all test input (especially tiffs files) ?

**Comment by Setnea** [comment]
@stork119 1,19 GB

**Comment by stork119** [comment]
It's to o big. Remove input files from repository. Compress them and upload on cloud or server (add link to source file in code or README)

**Comment by stork119** [comment]
@Setnea add short description to tests to inform what do they test. 
Pull this branch in FisherPC and check if it is working properly.

**Pull request merged**
